### ISSUE TITLE
wrong URLs in README

### ISSUE THREAD

**Issue by gn0st1c** [SmartThingsCommunity/Code#11]
README urls are not correct;
http://docs.smartthings.com/smartapp-web-services-developers-guide/tutorial-part1.html
http://docs.smartthings.com/smartapp-web-services-developers-guide/tutorial-part2.html

working urls;
http://docs.smartthings.com/en/latest/smartapp-web-services-developers-guide/tutorial-part1.html
http://docs.smartthings.com/en/latest/smartapp-web-services-developers-guide/tutorial-part2.html

**Comment by jimmyjames** [comment]
thanks for pointing that out, fixed now.
